name: Test and Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      - name: Analyze project source
        run: flutter analyze
      - name: Run tests
        run: flutter test

      # - name: Build Android Application Package
      #   run: flutter build apk
      # - name: Build Appbundle
      #   run: flutter build appbundle

      # - name: Build IOS
      #   run: flutter build ios --release --no-codesign

      # - name: Build MacOS
      #   run: flutter build macos

      - name: Build web
        run: flutter build web
